name: CD

on:
  push:
    branches:
      - trunk
  release:
    types:
      - published

jobs:
  release:
    name: Release Docker images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push latest version
        if: ${{ github.event_name == 'push' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}/makibot:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push stable version
        if: ${{ github.event_name == 'release' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}/makibot:${GITHUB_REF##*/},ghcr.io/${{ github.repository }}/makibot:stable
          cache-from: type=gha
          cache-to: type=gha,mode=max
  deploy:
    name: Deploy into my server
    needs: [release]
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    environment: public
    steps:
    - name: Execute a remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          docker-compose --project-directory docker/makibot pull
          docker-compose --project-directory docker/makibot up -d